version: '3.7'
services:
  jupyter:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
      - ${DATA_DIR}:/home/jovyan/data
      - ./CommonModule:/home/jovyan/CommonModule
      - ./startup-hooks:/usr/local/bin/before-notebook.d/
      - type: volume
        source: julia
        target: /opt/julia/
      - type: volume
        source: jupyter
        target: /home/jovyan/.jupyter

volumes:
  julia:
  jupyter:
