version: '3.7'
services:
  jupyter:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
      - ${DATA_DIR}:/home/jovyan/data
